apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-0610-llamacpp 
  janus-idp.io/tekton: codegen-0610-llamacpp
  backstage.io/kubernetes-id: codegen-0610-llamacpp
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: codegen-0610-llamacpp
resources: 
- application-dev.yaml