---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-0610-llamacpp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-0610-llamacpp 
  name: codegen-0610-llamacpp
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi